### ISSUE TITLE
Forbidden words wrong validation

### ISSUE THREAD

**Issue by stolktech** [friedt/kenteken-check-NL-RDW#1]
The current license plates forbidden words filter is incorrect, because you strip the dashes before the forbidden words check.

SS/SD/GVD are not allowed, but with dashes they are:
01-GVD-1 is forbidden, but 10-XG-VD is an existing license plate and should be allowed. Is this something you can update?

**Comment by friedt** [comment]
Hi, i understand what you are saying, thank you for mentioning, i will update this!

**Comment by brinkie** [comment]
Some clarification: xS-Dx-nn, xS-Sx-nn, nn-xS-Dx and nn-xS-Sx are all blocked but should be (and are) allowed, for example JS-DF-11 and 10-XS-SX.

Also the blocks for abbreviations for political parties have been set after the licence plates have been issued and people started to complain. For example the package blocks the use of VVD but 14-VVD-4 is a valid registration of a VW Transporter.

**Comment by friedt** [comment]
Yes, i understand this, but at this moment i took into account that it works for "voertuig categorie" : Personenauto's . 

These voertuigcategorieen are not yet taken into account : 
Brom- en Snorfietsen D of F
Aanhangwagens W
Opleggers O
Lichte bedrijfsauto’s (tot 3500 kg) V
Zware bedrijfsauto’s (boven 3500 kg) B
Motorfietsen M
Grensverkeer GV - altijd in combinatie met 4 cijfers
Land- en bosbouwtrekkers en Mobiele machines en MMBS'en  T
Land- en bosbouwaanhangwagens en verwisselbare getrokken uitrustingsstukken L

**Comment by friedt** [comment]
> The current license plates forbidden words filter is incorrect, because you strip the dashes before the forbidden words check.
> 
> SS/SD/GVD are not allowed, but with dashes they are:
> 01-GVD-1 is forbidden, but 10-XG-VD is an existing license plate and should be allowed. Is this something you can update?

1.0.6 has been published and bug fixed

**Comment by friedt** [comment]
> Some clarification: xS-Dx-nn, xS-Sx-nn, nn-xS-Dx and nn-xS-Sx are all blocked but should be (and are) allowed, for example JS-DF-11 and 10-XS-SX.
> 
> Also the blocks for abbreviations for political parties have been set after the licence plates have been issued and people started to complain. For example the package blocks the use of VVD but 14-VVD-4 is a valid registration of a VW Transporter.

this is now bugfixed and published on npm

**Comment by friedt** [comment]
> SS/SD/GVD are not allowed, but with dashes they are:

as the real dutch licenseplate is presented with dashes i only use dashes, but of course i can also change this, but at this moment i do not see the importancy of it
